[package]
name = "vfox"
version = "0.1.0-alpha.0"
edition = "2021"
license = "MIT"
description = "Interface to vfox plugins"

[dependencies]
mlua = { version = "0.9", features = ["lua54", "vendored"] }
