[package]
name = "vfox"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT"
description = "Interface to vfox plugins"
documentation = "https://docs.rs/vfox"
homepage = "https://github.com/jdx/vfox.rs"
repository = "https://github.com/jdx/vfox.rs"

[lib]
name = "vfox"
path = "src/lib.rs"

[[bin]]
name = "vfox-cli"
path = "src/bin.rs"

[dependencies]
bzip2 = "0.4.4"
flate2 = "1.0.30"
homedir = "0.2.1"
mlua = { version = "0.9", features = ["async", "lua54", "macros", "serialize", "vendored"] }
once_cell = "1"
reqwest = { version = "0.12", features = [] }
serde_json = "1"
tar = "0.4.40"
thiserror = "1"
tokio = { version = "1", features = ["macros", "fs"] }
xx = "0.3.0"
xz = "0.1.0"
zip = "1.2.3"

[dev-dependencies]
insta = "1"
#pretty_assertions = "1.4.0"

[workspace.metadata.release]
pre-release-hook = ["git", "cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
