[tools]
"cargo:cargo-edit" = "latest"
"cargo:git-cliff" = "latest"
"npm:prettier" = "latest"

[tasks.lint]
depends = ['lint:*']
[tasks."lint:prettier"]
run = "prettier -c ."
[tasks."lint:clippy"]
run = 'cargo clippy --all --all-features -- -D warnings'
[tasks."lint:fmt"]
run = 'cargo fmt --all -- --check'
